import type { Metadata } from "next";
import { Inter, Metrophobic } from "next/font/google";
import "./globals.scss";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-inter",
  display: "swap",
});

const metrophobic = Metrophobic({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-metrophobic",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${metrophobic.variable}`}>
        {children}
      </body>
    </html>
  );
}
